apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cobcserver
    name: cobcserver
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: cobcserver
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cobcserver
    name: cobcserver
  spec:
    replicas: 1
    selector:
      io.kompose.service: cobcserver
    strategy:
      resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cobcserver
      spec:
        containers:
        - image: ' '
          name: cobcserver
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - cobcserver
        from:
          kind: ImageStreamTag
          name: cobcserver:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cobcserver
    name: cobcserver
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: cobcserver
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cobcserver
    name: cobcserver
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cobcserver:latest
    postCommit: {}
    resources:
      limits:
        cpu: '1'
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    runPolicy: Serial
    source:
      contextDir: CobcServerDocker/
      git:
        ref: master
        uri: git@github.com:TW5860/CobcServer.git
        secrets:
          - secretSource:
              name: "ssh_private"
      type: Git
    strategy:
      dockerStrategy:
        secrets:
          - secretSource:
              name: "ssh-private"
              mountPath: "/root/.ssh/id_rsa"
          - secretSource:
              name: "ssh-public"
              mountPath: "/root/.ssh/id_rsa.pub"
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
kind: List
metadata: {}
